version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - /mnt/c/Users/ngtin/data/wordpress:/var/www/html
    depends_on:
       - wordpress

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    networks:
      - inception
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - /mnt/c/Users/ngtin/data/wordpress:/var/www/html
    secrets:
      - wp_admin_pass
      - wp_user_pass
      - wordpress_db_pass

  mariadb:
    image: mariadb:10.5
    networks:
      - inception
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/mysql_pass
    volumes:
      - /mnt/c/Users/ngtin/data/mariadb:/var/lib/mysql
    expose:
      - "3306"
    secrets:
      - mysql_pass

secrets:
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt
  wordpress_db_pass:
    file: ../secrets/wordpress_db_pass.txt
  mysql_pass:
    file: ../secrets/mysql_pass.txt

networks:
  inception:
    driver: bridge
