# services: nginx, wordpress, mariadb, bonus services.

# volumes: data persistence.

# networks: container communication.

# build and image directives.

# env_file or environment variables.

# It connects and configures everything in one place, so you can docker-compose up.



services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
#  wordpress:
#    build: ./requirements/wordpress
#    image: wordpress
#  mariadb:
#    build: ./requirements/mariadb
#    image: mariadb