#For mariadb → set up database, configure root user, create database.

FROM mariadb:10.5

# Optionally copy custom config
COPY my.cnf /etc/mysql/conf.d/

#Optionally run custom scripts
COPY init.sql /docker-entrypoint-initdb.d/
